[tool.black]
line-length = 88
target-version = ['py310']

[tool.flake8]
max-line-length = 88
extend-ignore = "E203,W503"

[tool.bandit]
exclude_dirs = ["tests", "venv", "env"]
skips = ["B101", "B104"]